import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "@/providers/ReactQueryProviders";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoExpo",
  description: "Generated by lee",
};

// app/layout.tsx

export default function RootLayout({
  children,
  modal, // 1. 반드시 modal 프롭을 추가해야 합니다.
}: {
  children: React.ReactNode;
  modal: React.ReactNode; // 2. 타입 정의도 잊지 마세요.
}) {
  return (
    <html>
      <body>
        <Navbar />
        <main className="pt-14">
          {children}
          {/* 3. children과 같은 레벨에 modal을 배치합니다. */}
          {modal}
        </main>
      </body>
    </html>
  );
}
