import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Image from "next/image";
import ReactQueryProviders from "@/util/ReactQueryProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PhotoExpo",
  description: "Generated by lee",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="navbar">
          <Link href="/">
            <Image
              src="/PhotoExpoLogo2.png"
              alt="PhotoExpo Logo"
              width={380}
              height={60}
              className="w-32 h-auto ml-0"
              priority
            />
          </Link>
          <Link href="/list">List</Link>
          <Link href="/user/info">MyPage</Link>
          <Link href="/login">Login</Link>
          <Link href="/join">Join</Link>
        </div>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
